name: K8s CI
on:
  - push
jobs:
    
  deploy:
    name: deploy to eks
    runs-on: ubuntu-latest
    steps:
      
      - name: Deploy project to eks
        uses: ianbelcher/eks-kubectl-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          eks_role_arn: ${{ secrets.EKS_ROLE_ARN }}
          args: apply -f https://raw.githubusercontent.com/obligatorioDevOps/k8s/main/obligatorio.yml
      

