name: K8s CI test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Install ingress controller
      run: minikube addons enable ingress     
    - name: Deploy to minikube containers and service
      run: kubectl apply -f https://raw.githubusercontent.com/obligatorioDevOps/k8s/main/obligatorio.yml
    - name: Delete ValidatingWebhookConfiguration
      run: kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
  
  deploy:
    name: deploy to eks
    runs-on: ubuntu-latest 
    steps:
      # --- #
      - name: Build and push CONTAINER_NAME
        uses: ianbelcher/eks-kubectl-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          eks_role_arn: ${{ secrets.EKS_ROLE_ARN }}
          args: apply -f https://raw.githubusercontent.com/obligatorioDevOps/k8s/main/obligatorio.yml
      # --- #

